# ████████╗███╗   ███╗██╗   ██╗██╗  ██╗
# ╚══██╔══╝████╗ ████║██║   ██║╚██╗██╔╝
#    ██║   ██╔████╔██║██║   ██║ ╚███╔╝
#    ██║   ██║╚██╔╝██║██║   ██║ ██╔██╗
#    ██║   ██║ ╚═╝ ██║╚██████╔╝██╔╝ ██╗
#    ╚═╝   ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝
#
# https://github.com/tmux/tmux

# Key Bindings

# Session management
bind-key -n M-s display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sesh' tv sesh

# Window/Pane management
bind-key -n M-n new-window
bind-key -n M-w kill-pane
bind-key -n M-W kill-window
bind-key -n M-Enter resize-pane -Z
bind-key -n M-q detach-client
bind-key -n M-d split-window -h -c "#{pane_current_path}"
bind-key -n M-D split-window -v -c "#{pane_current_path}"

# Switch panes
bind-key -n M-Left  select-pane -L
bind-key -n M-Right select-pane -R
bind-key -n M-Up    select-pane -U
bind-key -n M-Down  select-pane -D

# Resize panes
bind-key -n M-S-Left  resize-pane -L 5
bind-key -n M-S-Right resize-pane -R 5
bind-key -n M-S-Up    resize-pane -U 5
bind-key -n M-S-Down  resize-pane -D 5

# Switch windows
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5

# Fix escape-time delay (default is 500ms, which feels laggy)
set -s escape-time 0

# Better Terminal Compatibility
set -g default-terminal "tmux-256color"
# Enable RGB (True Color) support
set -as terminal-features ",xterm-256color:RGB"

set -g base-index 1
set -g detach-on-destroy off
set -g renumber-windows on
set -g set-clipboard on

# status bar
set -g status-interval 3
set -g status-justify absolute-centre
set -g status-left "#[fg=blue,bold]#S "
set -g status-left-length 100
set -g status-position top
set -g status-right "#[fg=white,nobold]#(gitmux -cfg $HOME/.config/tmux/gitmux.yml)"
set -g status-right-length 300
set -g status-style 'bg=default'

# windows
set -g window-status-current-format '#[fg=magenta](#I) #W'
set -g window-status-format '#[fg=gray](#I) #W'
set -g window-status-separator "  "
set -gw automatic-rename on
set -gw automatic-rename-format '#{b:pane_current_command}'

# panes
set -g pane-active-border-style 'fg=black,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# plugin settings
set -g @floatx-bind H

# plugins
set -g @plugin 'omerxx/tmux-floax'

set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'
