#   ███████╗███████╗███████╗██╗  ██╗
#   ██╔════╝██╔════╝██╔════╝██║  ██║
#   ███████╗█████╗  ███████╗███████║
#   ╚════██║██╔══╝  ╚════██║██╔══██║
#   ███████║███████╗███████║██║  ██║
#   ╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝

# https://github.com/joshmedeski/sesh

strict_mode = false

blacklist = ["scratch"]

sort_order = ["tmux", "config", "zoxide"]
dir_length = 2

[default_session]
statup_command = "nvim +GoToFile"
preview_command = "eza --all --oneline --icons --git --color=always --group-directories-first {}"

# configs

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "opencode"
path = "~/dotfiles/.config/opencode"
startup_command = "nvim opencode.json"
preview_command = "bat --language=json --style=snip --color=always ~/dotfiles/.config/opencode/opencode.json"

[[session]]
name = "wezterm"
path = "~/dotfiles/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[wildcard]]
pattern = "~/github/*"
startup_command = "nvim"

[[wildcard]]
pattern = "~/ws/*"
startup_command = "nvim"
