format = """
$directory\
$git_branch\
$git_status
$character
"""

right_format = """$python"""

add_newline = true

[character]
success_symbol = '[➜](bold green)'

[directory]
truncation_length = 1

[git_branch]
format = '[$symbol$branch]($style)'
style = 'bold red'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
detect_folders = ['.venv']
