#   ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗ 
#   ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
#   ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
#   ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝ 
#   ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║     
#   ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝     

# https://github.com/starship/starship

format = """
$directory\
$character
"""

right_format = """$python"""

add_newline = true

[character]
success_symbol = '[➜](bold green)'

[directory]
truncation_length = 1

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
detect_folders = ['.venv']
