default_provider = "pass"

[providers.pass]
type = "password-store"
prefix = "fnox/"

[secrets]
MISE_GITHUB_TOKEN= { provider = "pass", value = "MISE_GITHUB_TOKEN" }
GITHUB_PACKAGE_TOKEN= { provider = "pass", value = "GITHUB_PACKAGE_TOKEN" }
