#   ████████╗███████╗██╗     ███████╗██╗   ██╗██╗███████╗██╗ ██████╗ ███╗   ██╗
#   ╚══██╔══╝██╔════╝██║     ██╔════╝██║   ██║██║██╔════╝██║██╔═══██╗████╗  ██║
#      ██║   █████╗  ██║     █████╗  ██║   ██║██║███████╗██║██║   ██║██╔██╗ ██║
#      ██║   ██╔══╝  ██║     ██╔══╝  ╚██╗ ██╔╝██║╚════██║██║██║   ██║██║╚██╗██║
#      ██║   ███████╗███████╗███████╗ ╚████╔╝ ██║███████║██║╚██████╔╝██║ ╚████║
#      ╚═╝   ╚══════╝╚══════╝╚══════╝  ╚═══╝  ╚═╝╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝

# https://github.com/alexpasmantier/television

# General settings
tick_rate = 50
default_channel = "files"

# Shell settings
shell = "zsh"

# History settings
history_size = 200
global_history = false

[ui]

# Theme
theme = "catppuccin-macchiato-flamingo.toml"

[previewers.file]
theme = "Catppuccin Macchiato"

[shell_integration.channel_triggers]
"git-branch" = ["git checkout", "git branch"]
"dirs" = ["cd", "ls", "rmdir"]
"files" = ["cat", "less", "vim"]
