#   ███╗   ███╗██╗███████╗███████╗
#   ████╗ ████║██║██╔════╝██╔════╝
#   ██╔████╔██║██║███████╗█████╗  
#   ██║╚██╔╝██║██║╚════██║██╔══╝  
#   ██║ ╚═╝ ██║██║███████║███████╗
#   ╚═╝     ╚═╝╚═╝╚══════╝╚══════╝

# https://github.com/jdx/mise

[tools]
aws = "latest"
bun = "latest"
go = "1.24"
node = "lts"
python = "3.14"

antigravity-cli = "latest"
arduino-cli = "1.5.1"
azure = "2.86.0"
bat = "0.26.1"
delta = "0.19.2"
eza = "0.23.4"
fd = "10.4.2"
fnox = "1.19.0"
fx = "39.2.0"
glow = "2.1.2"
helm = "4.2.0"
jj = "0.39.0"
jq = "jq-1.8.1"
k9s = "0.50.18"
kubectl = "1.36.1"
lazygit = "0.60.0"
mongosh = "2.8.2"
neovim = "0.12.0"
opencode = "latest"
packer = "1.9.4"
pi = "latest"
ripgrep = "15.1.0"
rtk = "latest"
television = "0.15.4"
terraform = "1.14.8"
terragrunt = "v0.99.5"
tree-sitter = "0.26.7"
tmux = "3.6a"
xh = "0.25.3"
yq = "4.52.5"
zoxide = "0.9.9"

"github:arl/gitmux" = "v0.11.5"
"github:basecamp/fizzy-cli" = "v3.0.3"
"github:joshmedeski/sesh" = "v2.24.2"
"github:rossmacarthur/sheldon" = "0.8.5"

[env]
MISE_NPM_BUN = true
EDITOR = "nvim"

[settings]
experimental = true
